apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-depl
  namespace: default
  labels:
    app: ecommerce-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-depl
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: ecommerce-depl
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - 'until pg_isready -h postgres -U postgres; do echo "waiting for postgres"; sleep 2; done'
      containers:
        - name: ecommerce-api
          image: ecommerce-learn-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?schema=public"
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
            - name: AZURE_STORAGE_CONTAINER
              value: "product-images"

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ecommerce-depl
  ports:
    - port: 80
      targetPort: 3000
