{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-api.secretName" . }}
  labels:
    {{- include "ecommerce-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "ecommerce-api.databaseUrl" . | quote }}
  AZURE_STORAGE_CONNECTION_STRING: {{ include "ecommerce-api.azureStorageConnectionString" . | quote }}
{{- end }}
